from flask import Request, Response

from api.proxy.proxy_interface import ProxyInterface
from api.common.response_formatter import ResponseFormatter


class ActionsResponsesGenerator(ProxyInterface):
    """Actions responses generator service that is responsible for searching a specific document."""

    def handle_request(self, user_request: Request) -> Response:
        """
        Manage an action request submitted by a user to give an adequate response.

        :param user_request: An action request submitted by a user.
        :return: The response generated by the actions service.
        """

        # Get action sent by the user
        action: str = user_request.get_json()['action']

        # Get documents from a database
        from api.persistence_requests import data_importer
        documents: list[dict] = data_importer.documents

        for document in documents:
            # Give a response based on a found document
            if document['id'] == action:
                return ResponseFormatter.get_recognized_response(document)

        # Give a no recognized intent
        return ResponseFormatter.get_recognized_response({'id': action})
