from abc import ABC


class IntentRecognizerResponse(ABC):
    """Base class for a response object generated by an intent recognizer."""

    def __init__(self, recognition_status: bool):
        """
        Constructor.

        :param recognition_status: A boolean value that describes if the intent was recognized.
        """
        self.recognition_status: bool = recognition_status
